const MAX_DAYS = {
  ONE_MINUTE: 30,
  THREE_MINUTE: 60,
  FIVE_MINUTE: 100,
  TEN_MINUTE: 100,
  FIFTEEN_MINUTE: 200,
  THIRTY_MINUTE: 200,
  ONE_HOUR: 400,
  ONE_DAY: 2000,
};

const INTERVAL_MAP = {
  ONE_MINUTE: 'M1',
  THREE_MINUTE: 'M3',
  FIVE_MINUTE: 'M5',
  TEN_MINUTE: 'M10',
  FIFTEEN_MINUTE: 'M15',
  THIRTY_MINUTE: 'M30',
  ONE_HOUR: 'H1',
  ONE_DAY: 'D1',
};

module.exports = { MAX_DAYS, INTERVAL_MAP };
